#openai_key = "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"
#openai_api_key = "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"
openai_key = "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"
